Initiate two matrices of 4*3 and 3*4 resepctively with any numbers you wish.

Write a function which takes as input
the two matrices, perfroms matrix multiplication and returns the resultant 4*4 matrix. Don't use the numpy functions for matrix

multiplication. You can however use numpy to initialize the matrices.

In [1]:
import numpy as np  # Only using numpy to initialize matrices

In [4]:
def matrices_initializer():
    # Initialize two matrices with random numbers
    matrix1 = np.random.rand(4, 3)
    matrix2 = np.random.rand(3, 4)
    return matrix1, matrix2

def matrix_multiply_calculation(matrix1, matrix2):
    if matrix1.shape[1] != matrix2.shape[0]:
        raise ValueError("Matrix dimensions are not compatible for multiplication")

    # Initialize the result matrix with zeros
    result = np.zeros((matrix1.shape[0], matrix2.shape[1]))

    # Perform matrix multiplication
    for i in range(matrix1.shape[0]):
        for j in range(matrix2.shape[1]):
            for k in range(matrix1.shape[1]):
                result[i, j] += matrix1[i, k] * matrix2[k, j]

    return result

In [6]:
#creating the drive programme
if __name__=="__main__":
  # Initialize the matrices
  matrix1, matrix2 = matrices_initializer()
  # Perform matrix multiplication
  result_matrix = matrix_multiply_calculation(matrix1, matrix2)
  # Print the result matrix
  print(f"the matrix multiplication output is {result_matrix} and its type is {type(result_matrix)}")

the matrix multiplication output is [[0.80511297 0.8759565  0.89066297 1.24382157]
 [0.36225529 0.15848753 0.14555884 0.23141129]
 [0.72262129 0.8577292  0.89728646 1.26352789]
 [1.34538307 0.93169829 0.96654309 1.46391785]] and its type is <class 'numpy.ndarray'>
